(declare (unit interpreter))
(use extras)

(define (interpreter parse compile evaluate)
  (let loop ((iter 1))
    (printf "#;~a> " iter)
      (let ((expr (read-line)))
        (if (eqv? expr #!eof)
          (begin (display "quit") (newline))
          (let ((ast (parse expr)))
            (compile ast) (newline)
            (display #\u2192) (display " ")
            (compile (evaluate ast)) (newline)
            (loop (+ iter 1)))))))
