(require-extension lalr-driver)
(define simply-typed-parser
  (lr-driver
    '#(((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* -19))
       ((*default* -17))
       ((*default* -18))
       ((*default* *error*) (ID 12))
       ((*default* -6))
       ((*default* -3))
       ((*default* -2))
       ((*default* -16))
       ((*default* *error*)
        (*eoi* 16)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15))
       ((*default* *error*)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15)
        (RPAREN 19))
       ((*default* *error*) (COLON 20))
       ((*default* *error*) (DOT 21))
       ((*default* -14) (COMMA 22))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* -1) (*eoi* accept))
       ((*default* -5))
       ((*default* -21))
       ((*default* -4))
       ((*default* *error*) (ID 25) (LPAREN 24))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* *error*) (ID 12))
       ((*default* *error*)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15)
        (RPAREN 31))
       ((*default* *error*) (ID 25) (LPAREN 24))
       ((*default* -7) (ID 25))
       ((*default* -13) (ARROW 34))
       ((*default* -10))
       ((*default* -9))
       ((*default* -20) (ID 6) (BOOL 4) (NUM 3) (BUILTIN 2) (LPAREN 15))
       ((*default* -15))
       ((*default* -22))
       ((*default* *error*) (ARROW 34) (RPAREN 35))
       ((*default* -8))
       ((*default* *error*) (ID 25) (LPAREN 24))
       ((*default* -11))
       ((*default* -12) (ARROW 34)))
    (vector
      '((9 . 7) (8 . 8) (2 . 9) (1 . 10))
      '((9 . 7) (8 . 8) (2 . 9) (1 . 11))
      '()
      '()
      '()
      '((7 . 13) (6 . 14))
      '()
      '()
      '()
      '()
      '((10 . 17) (8 . 18) (2 . 9))
      '((10 . 17) (8 . 18) (2 . 9))
      '()
      '()
      '()
      '((9 . 7) (8 . 8) (2 . 9) (1 . 23))
      '()
      '()
      '()
      '()
      '((5 . 26) (4 . 27) (3 . 28))
      '((9 . 7) (8 . 8) (2 . 9) (1 . 29))
      '((7 . 30) (6 . 14))
      '((10 . 17) (8 . 18) (2 . 9))
      '((5 . 32) (4 . 27) (3 . 28))
      '((3 . 33))
      '()
      '()
      '()
      '((10 . 17) (8 . 18) (2 . 9))
      '()
      '()
      '()
      '()
      '((5 . 36) (4 . 27) (3 . 28))
      '()
      '())
    (vector
      '()
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          $1))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 1 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 1 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 1 $2)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          (___push 2 1 (make-app $1 $2))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 2 (make-var $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 3 (cons $1 '()))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          (___push 2 3 (cons $1 $2))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 4 (list->string $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 5 (make-type $1 #f))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 5 $2)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 5 (make-type $1 $3))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 6 (make-var $1 $3))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 7 (cons $1 '()))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 7 (cons $1 $3))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 8 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 8 (make-num $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 8 (make-bool $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 8 (make-builtin $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($4 (vector-ref ___stack (- ___sp 1)))
               ($3 (vector-ref ___stack (- ___sp 3)))
               ($2 (vector-ref ___stack (- ___sp 5)))
               ($1 (vector-ref ___stack (- ___sp 7))))
          (___push 4 9 (make-fun $2 $4))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 10 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 10 $2))))))

