(require-extension lalr-driver)
(define simply-typed-parser
  (lr-driver
    '#(((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* -13))
       ((*default* -11))
       ((*default* -12))
       ((*default* *error*) (ID 12))
       ((*default* -6))
       ((*default* -3))
       ((*default* -2))
       ((*default* -10))
       ((*default* *error*)
        (*eoi* 16)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15))
       ((*default* *error*)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15)
        (RPAREN 19))
       ((*default* *error*) (COLON 20))
       ((*default* *error*) (DOT 21))
       ((*default* -8) (ID 12))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* -1) (*eoi* accept))
       ((*default* -5))
       ((*default* -15))
       ((*default* -4))
       ((*default* *error*) (ID 24))
       ((*default* *error*)
        (ID 6)
        (LAMBDA 5)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 1))
       ((*default* -9))
       ((*default* *error*)
        (ID 6)
        (BOOL 4)
        (NUM 3)
        (BUILTIN 2)
        (LPAREN 15)
        (RPAREN 26))
       ((*default* -7))
       ((*default* -14) (ID 6) (BOOL 4) (NUM 3) (BUILTIN 2) (LPAREN 15))
       ((*default* -16)))
    (vector
      '((6 . 7) (5 . 8) (2 . 9) (1 . 10))
      '((6 . 7) (5 . 8) (2 . 9) (1 . 11))
      '()
      '()
      '()
      '((4 . 13) (3 . 14))
      '()
      '()
      '()
      '()
      '((7 . 17) (5 . 18) (2 . 9))
      '((7 . 17) (5 . 18) (2 . 9))
      '()
      '()
      '((4 . 22) (3 . 14))
      '((6 . 7) (5 . 8) (2 . 9) (1 . 23))
      '()
      '()
      '()
      '()
      '()
      '((6 . 7) (5 . 8) (2 . 9) (1 . 25))
      '()
      '((7 . 17) (5 . 18) (2 . 9))
      '()
      '((7 . 17) (5 . 18) (2 . 9))
      '())
    (vector
      '()
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          $1))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 1 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 1 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 1 $2)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          (___push 2 1 (make-app $1 $2))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 2 (make-var $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 3 (*make-var $1 $3))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 4 (cons $1 '()))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($2 (vector-ref ___stack (- ___sp 1)))
               ($1 (vector-ref ___stack (- ___sp 3))))
          (___push 2 4 (cons $1 $2))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 5 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 5 (make-num $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 5 (make-bool $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1))))
          (___push 1 5 (make-builtin $1))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($4 (vector-ref ___stack (- ___sp 1)))
               ($3 (vector-ref ___stack (- ___sp 3)))
               ($2 (vector-ref ___stack (- ___sp 5)))
               ($1 (vector-ref ___stack (- ___sp 7))))
          (___push 4 6 (make-fun $2 $4))))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($1 (vector-ref ___stack (- ___sp 1)))) (___push 1 7 $1)))
      (lambda (___stack ___sp ___goto-table ___push yypushback)
        (let* (($3 (vector-ref ___stack (- ___sp 1)))
               ($2 (vector-ref ___stack (- ___sp 3)))
               ($1 (vector-ref ___stack (- ___sp 5))))
          (___push 3 7 $2))))))

